### ISSUE TITLE
encoding of the files?

### ISSUE THREAD

**Issue by adham89** [xianneo/OurMetrics#1]
Hi,

while running the program I encounterd the following problem

java.lang.NullPointerException
    at util.ProjectUtil.getJavaProjects(ProjectUtil.java:33)
    at test.ProjectUtilTest.<init>(ProjectUtilTest.java:33)
    at main.Entrance.main(Entrance.java:19)

now what should be passed into the parameters in the both methods so it doesnt give this error? 

thanks

**Comment by xianneo** [comment]
Hello,

 I'm sorry my bad coding style confused you . Because it is an exercise of code metric tools when I study CS in university.

Now we start a new project called Perfume.You can metirc your code by using it.

URL:    https://github.com/LiuHongtao/Perfume
